//! Embeds the runtime JS listed in `js/manifest.json` (PR #15570 layout).
//! A missing or malformed manifest, or a listed file that does not exist,
//! fails the build: nothing is skipped.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("js");
    let manifest_path = dir.join("manifest.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let manifest = std::fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("{}: {e}", manifest_path.display()));
    let mut out = String::from("// Generated by build.rs from js/manifest.json.\n");
    for list in ["repl", "agent"] {
        let files = json_string_list(&manifest, list)
            .unwrap_or_else(|| panic!("js/manifest.json: missing \"{list}\" list"));
        let constant = list.to_uppercase();
        let _ = writeln!(out, "pub static {constant}_SCRIPTS: &[(&str, &str)] = &[");
        for file in files {
            let path = dir.join(&file);
            assert!(path.is_file(), "js/manifest.json lists {file}, which does not exist");
            println!("cargo:rerun-if-changed={}", path.display());
            let _ =
                writeln!(out, "    ({file:?}, include_str!({:?})),", path.display().to_string());
        }
        out.push_str("];\n");
    }
    let guide = dir.join("guide.md");
    println!("cargo:rerun-if-changed={}", guide.display());
    let _ =
        writeln!(out, "pub static GUIDE: &str = include_str!({:?});", guide.display().to_string());
    let target = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("js_bundle.rs");
    std::fs::write(&target, out).expect("write js_bundle.rs");
}

/// The string array under `"key": [...]` in a flat JSON manifest.
fn json_string_list(text: &str, key: &str) -> Option<Vec<String>> {
    let start = text.find(&format!("\"{key}\""))?;
    let rest = &text[start..];
    let open = rest.find('[')?;
    let close = rest[open..].find(']')? + open;
    Some(
        rest[open + 1..close]
            .split(',')
            .map(|item| item.trim().trim_matches('"').to_owned())
            .filter(|item| !item.is_empty())
            .collect(),
    )
}
